/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/matrix_test.check" instead.
 */

#include <check.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "../s21_matrix.h"
#include "../s21_matrix_helpers.h"

START_TEST(create_no_mistake_square) {
  for (int i = 1; i < 100; i++) {
    matrix_t matrix;
    int result = s21_create_matrix(i, i, &matrix);
    ck_assert_int_eq(OK, result);
    ck_assert_int_eq(i, matrix.columns);
    ck_assert_int_eq(i, matrix.columns);
    free_memory(&matrix);
  }
}
END_TEST

START_TEST(create_no_mistake_vector_1) {
  for (int i = 2; i < 100; i += 2) {
    matrix_t matrix;
    int result = s21_create_matrix(1, i, &matrix);
    ck_assert_int_eq(OK, result);
    ck_assert_int_eq(1, matrix.rows);
    ck_assert_int_eq(i, matrix.columns);
    free_memory(&matrix);
  }
}
END_TEST

START_TEST(create_no_mistake_vector_2) {
  for (int i = 1; i < 120; i += 3) {
    matrix_t matrix;
    int result = s21_create_matrix(i, 1, &matrix);
    ck_assert_int_eq(OK, result);
    ck_assert_int_eq(i, matrix.rows);
    ck_assert_int_eq(1, matrix.columns);
    free_memory(&matrix);
  }
}
END_TEST

START_TEST(create_no_mistake_rectangle) {
  for (int i = 1; i < 50; i += 2) {
    matrix_t matrix;
    int result = s21_create_matrix(i + 1, 51 - i, &matrix);
    ck_assert_int_eq(OK, result);
    ck_assert_int_eq(i + 1, matrix.rows);
    ck_assert_int_eq(51 - i, matrix.columns);
    free_memory(&matrix);
  }
}
END_TEST

START_TEST(create_mistake_incorrect_size_1) {
  for (int i = 0; i > -50; i--) {
    matrix_t matrix;
    int result = s21_create_matrix(i, 1, &matrix);
    ck_assert_int_eq(INCORRECT_MATRIX, result);
  }
}
END_TEST

START_TEST(create_mistake_incorrect_size_2) {
  for (int i = 0; i > -50; i--) {
    matrix_t matrix;
    int result = s21_create_matrix(1, i, &matrix);
    ck_assert_int_eq(INCORRECT_MATRIX, result);
  }
}
END_TEST

START_TEST(create_mistake_null_poiner) {
  matrix_t *matrix = NULL;
  int result = s21_create_matrix(1, 1, matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
}
END_TEST

START_TEST(remove_matrix_correct) {
  for (int i = 1; i < 50; i++) {
    matrix_t matrix;
    int result = s21_create_matrix(1, i, &matrix);
    ck_assert_int_eq(OK, result);
    s21_remove_matrix(&matrix);
    ck_assert_ptr_null(matrix.matrix);
    ck_assert_int_eq(0, matrix.rows);
    ck_assert_int_eq(0, matrix.columns);
  }
}
END_TEST

START_TEST(remove_matrix_incorrect_pointer) {
  for (int i = 1; i < 50; i++) {
    matrix_t matrix;
    int result = s21_create_matrix(1, i, &matrix);
    ck_assert_int_eq(OK, result);
    free_memory(&matrix);
    s21_remove_matrix(&matrix);
    ck_assert_ptr_null(matrix.matrix);
    ck_assert_int_eq(0, matrix.rows);
    ck_assert_int_eq(0, matrix.columns);
  }
}
END_TEST

START_TEST(eq_square_matrix) {
  for (int i = 1; i < 100; i++) {
    matrix_t matrix1, matrix2;
    int result1 = s21_create_matrix(i, i, &matrix1);
    int result2 = s21_create_matrix(i, i, &matrix2);
    write_iteratively_matrix(&matrix1, (double)i, (double)i / 2);
    write_iteratively_matrix(&matrix2, (double)i, (double)i / 2);
    ck_assert_int_eq(OK, result1);
    ck_assert_int_eq(OK, result2);
    ck_assert_int_eq(SUCCESS, s21_eq_matrix(&matrix1, &matrix2));
    s21_remove_matrix(&matrix1);
    s21_remove_matrix(&matrix2);
  }
}
END_TEST

START_TEST(eq_rectangle_matrix) {
  for (int i = 1; i < 50; i++) {
    matrix_t matrix1, matrix2;
    int result1 = s21_create_matrix(i, 50 - i, &matrix1);
    int result2 = s21_create_matrix(i, 50 - i, &matrix2);
    write_iteratively_matrix(&matrix1, (double)i / 5, (double)i);
    write_iteratively_matrix(&matrix2, (double)i / 5, (double)i);
    ck_assert_int_eq(OK, result1);
    ck_assert_int_eq(OK, result2);
    ck_assert_int_eq(SUCCESS, s21_eq_matrix(&matrix1, &matrix2));
    s21_remove_matrix(&matrix1);
    s21_remove_matrix(&matrix2);
  }
}
END_TEST

START_TEST(eq_matrix_same_size) {
  for (int i = 1; i < 50; i++) {
    matrix_t matrix1, matrix2;
    int result1 = s21_create_matrix(i, 50 - i, &matrix1);
    int result2 = s21_create_matrix(i, 50 - i, &matrix2);
    write_iteratively_matrix(&matrix1, (double)i / 4, (double)i);
    write_iteratively_matrix(&matrix2, (double)i / 5, (double)i);
    ck_assert_int_eq(OK, result1);
    ck_assert_int_eq(OK, result2);
    ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
    s21_remove_matrix(&matrix1);
    s21_remove_matrix(&matrix2);
  }
}
END_TEST

START_TEST(eq_matrix_diff_size) {
  for (int i = 1; i < 50; i++) {
    matrix_t matrix1, matrix2;
    int result1 = s21_create_matrix(2 * i, 50 - i, &matrix1);
    int result2 = s21_create_matrix(i, i, &matrix2);
    write_iteratively_matrix(&matrix1, (double)i / 4, (double)i);
    write_iteratively_matrix(&matrix2, (double)i / 5, (double)i);
    ck_assert_int_eq(OK, result1);
    ck_assert_int_eq(OK, result2);
    ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
    s21_remove_matrix(&matrix1);
    s21_remove_matrix(&matrix2);
  }
}
END_TEST

START_TEST(eq_matrix_wrong_matrix) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  write_iteratively_matrix(&matrix1, (double)1 / 4, (double)1);
  write_iteratively_matrix(&matrix2, (double)1 / 4, (double)1);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix1.rows = 0;
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  matrix1.rows = 2;
  matrix1.columns = 0;
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  matrix1.columns = 2;
  matrix2.columns = 0;
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  matrix2.columns = 2;
  matrix2.rows = 0;
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  matrix2.rows = 2;
  matrix1.matrix[0][0] = 0;
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  matrix2.matrix[0][0] = 0;
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&matrix1, &matrix2));
  s21_remove_matrix(&matrix1);
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
  s21_remove_matrix(&matrix2);
  ck_assert_int_eq(FAILURE, s21_eq_matrix(&matrix1, &matrix2));
}
END_TEST

START_TEST(sum_square_2x2) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(2, 2, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&expected_result, (double)2., (double)2.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)20.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)10., (double)20.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)10., (double)50.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)10., (double)50.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)0., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)0., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-1., (double)-1.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)5., (double)0.);
  write_iteratively_matrix(&matrix2, (double)10., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)15., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)2.);
  write_iteratively_matrix(&matrix2, (double)5., (double)-1.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)15., (double)1.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)2., (double)2.);
  write_iteratively_matrix(&matrix2, (double)5., (double)-2.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)7., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sum_vector) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(1, 5, &matrix1);
  int result2 = s21_create_matrix(1, 5, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(1, 5, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&expected_result, (double)2., (double)2.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)20.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)10., (double)20.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)404., (double)404.1);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)404., (double)404.1);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)404., (double)404.1);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)404., (double)404.1);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)3.);
  write_iteratively_matrix(&matrix2, (double)15., (double)0.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)25., (double)3.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)3.);
  write_iteratively_matrix(&matrix2, (double)2., (double)1.);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)3., (double)4.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sum_matrix_3x3) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(3, 3, &matrix1);
  int result2 = s21_create_matrix(3, 3, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix_t result, expected_result;
  result2 = s21_create_matrix(3, 3, &expected_result);
  matrix1.matrix[0][0] = 34.2;
  matrix2.matrix[0][0] = 4.3;
  expected_result.matrix[0][0] = 38.5;
  matrix1.matrix[0][1] = 1.;
  matrix2.matrix[0][1] = 2.2;
  expected_result.matrix[0][1] = 3.2;
  matrix1.matrix[0][2] = -7.4;
  matrix2.matrix[0][2] = 7.5;
  expected_result.matrix[0][2] = 0.1;
  matrix1.matrix[1][0] = -0.1;
  matrix2.matrix[1][0] = -0.2;
  expected_result.matrix[1][0] = -0.3;
  matrix1.matrix[1][1] = 0.;
  matrix2.matrix[1][1] = -0.5;
  expected_result.matrix[1][1] = -0.5;
  matrix1.matrix[1][2] = 9.9;
  matrix2.matrix[1][2] = -10;
  expected_result.matrix[1][2] = -0.1;
  matrix1.matrix[2][0] = 9.9;
  matrix2.matrix[2][0] = 0.1;
  expected_result.matrix[2][0] = 10.;
  matrix1.matrix[2][1] = 0.01;
  matrix2.matrix[2][1] = 0.1;
  expected_result.matrix[2][1] = 0.11;
  matrix1.matrix[2][2] = 0.1;
  matrix2.matrix[2][2] = -0.11;
  expected_result.matrix[2][2] = -0.01;
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sum_matrix_random) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(20, 17, &matrix1);
  int result2 = s21_create_matrix(20, 17, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix_t result, expected_result;
  write_random_matrix(&matrix1);
  result2 = s21_create_matrix(20, 17, &expected_result);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  for (int i = 0; i < 20; i++) {
    for (int j = 0; j < 17; j++) {
      expected_result.matrix[i][j] = matrix1.matrix[i][j];
    }
  }
  for (int i = 0; i < 20; i++) {
    for (int j = 0; j < 17; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sum_incorrect_matrix) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  write_iteratively_matrix(&matrix1, (double)1 / 4, (double)1);
  write_iteratively_matrix(&matrix2, (double)1 / 4, (double)1);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix1.columns = 0;
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  matrix1.columns = 2;
  matrix2.rows = 0;
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
}
END_TEST

START_TEST(sum_wrong_size) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(3, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  write_iteratively_matrix(&matrix1, (double)1 / 4, (double)1);
  write_iteratively_matrix(&matrix2, (double)1 / 4, (double)1);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  result1 = s21_sum_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(CALCULATION_ERROR, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(sub_square_2x2) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(2, 2, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)20.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)10., (double)20.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)10., (double)50.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-10., (double)-50.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)0., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)2., (double)2.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)1., (double)1.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)5., (double)0.);
  write_iteratively_matrix(&matrix2, (double)10., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-5., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)2.);
  write_iteratively_matrix(&matrix2, (double)5., (double)-1.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)5., (double)3.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)2., (double)2.);
  write_iteratively_matrix(&matrix2, (double)5., (double)-2.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-3., (double)4.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sub_vector) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(1, 5, &matrix1);
  int result2 = s21_create_matrix(1, 5, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)1., (double)1.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(1, 5, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&expected_result, (double)0., (double)0.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)20.);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)10., (double)20.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  write_iteratively_matrix(&matrix2, (double)404., (double)404.1);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-404., (double)-404.1);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)404., (double)404.1);
  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)404., (double)404.1);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)10., (double)3.);
  write_iteratively_matrix(&matrix2, (double)15., (double)0.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-5., (double)3.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)3.);
  write_iteratively_matrix(&matrix2, (double)2., (double)1.);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)-1., (double)2.);
  for (int i = 0; i < 1; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sub_matrix_3x3) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(3, 3, &matrix1);
  int result2 = s21_create_matrix(3, 3, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix_t result, expected_result;
  result2 = s21_create_matrix(3, 3, &expected_result);
  matrix1.matrix[0][0] = 34.2;
  matrix2.matrix[0][0] = 4.3;
  expected_result.matrix[0][0] = 29.9;
  matrix1.matrix[0][1] = 1.;
  matrix2.matrix[0][1] = 2.2;
  expected_result.matrix[0][1] = -1.2;
  matrix1.matrix[0][2] = -7.4;
  matrix2.matrix[0][2] = 7.5;
  expected_result.matrix[0][2] = -14.9;
  matrix1.matrix[1][0] = -0.1;
  matrix2.matrix[1][0] = -0.2;
  expected_result.matrix[1][0] = 0.1;
  matrix1.matrix[1][1] = 0.;
  matrix2.matrix[1][1] = -0.5;
  expected_result.matrix[1][1] = 0.5;
  matrix1.matrix[1][2] = 9.9;
  matrix2.matrix[1][2] = -10;
  expected_result.matrix[1][2] = 19.9;
  matrix1.matrix[2][0] = 9.9;
  matrix2.matrix[2][0] = 0.1;
  expected_result.matrix[2][0] = 9.8;
  matrix1.matrix[2][1] = 0.01;
  matrix2.matrix[2][1] = 0.1;
  expected_result.matrix[2][1] = -0.09;
  matrix1.matrix[2][2] = 0.1;
  matrix2.matrix[2][2] = -0.11;
  expected_result.matrix[2][2] = 0.21;
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sub_matrix_random) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(20, 17, &matrix1);
  int result2 = s21_create_matrix(20, 17, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix_t result, expected_result;
  write_random_matrix(&matrix1);
  result2 = s21_create_matrix(20, 17, &expected_result);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  for (int i = 0; i < 20; i++) {
    for (int j = 0; j < 17; j++) {
      expected_result.matrix[i][j] = matrix1.matrix[i][j];
    }
  }
  for (int i = 0; i < 20; i++) {
    for (int j = 0; j < 17; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(sub_incorrect_matrix) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  write_iteratively_matrix(&matrix1, (double)1 / 4, (double)1);
  write_iteratively_matrix(&matrix2, (double)1 / 4, (double)1);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix1.columns = 0;
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  matrix1.columns = 2;
  matrix2.rows = 0;
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
}
END_TEST

START_TEST(sub_wrong_size) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(3, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  write_iteratively_matrix(&matrix1, (double)1 / 4, (double)1);
  write_iteratively_matrix(&matrix2, (double)1 / 4, (double)1);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  result1 = s21_sub_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(CALCULATION_ERROR, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(mult_number_square_2x2) {
  srand(time(NULL));
  matrix_t matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);

  for (int count = 0; count < 100; count++) {
    matrix_t result_matrix;
    double multiplier =
        (double)(rand()) / RAND_MAX * pow(-1., rand() % 2) * ULONG_MAX;
    write_random_matrix(&matrix);
    result = s21_mult_number(&matrix, multiplier, &result_matrix);
    for (int i = 0; i < 2; i++) {
      for (int j = 0; j < 2; j++) {
        ck_assert_ldouble_eq_tol(result_matrix.matrix[i][j],
                                 multiplier * matrix.matrix[i][j], 0.000001);
      }
    }
    s21_remove_matrix(&result_matrix);
  }
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(mult_number_random_size) {
  srand(time(NULL));
  for (int count = 0; count < 100; count++) {
    matrix_t matrix, result_matrix;
    int rows = (int)rand() % 100 + 1, columns = (int)rand() % 100 + 1;
    double multiplier =
        (double)(rand()) / RAND_MAX * pow(-1., rand() % 2) * ULONG_MAX;
    int result = s21_create_matrix(rows, columns, &matrix);
    ck_assert_int_eq(OK, result);

    write_random_matrix(&matrix);
    result = s21_mult_number(&matrix, multiplier, &result_matrix);
    for (int i = 0; i < rows; i++) {
      for (int j = 0; j < columns; j++) {
        ck_assert_ldouble_eq_tol(result_matrix.matrix[i][j],
                                 multiplier * matrix.matrix[i][j], 0.000001);
      }
    }
    s21_remove_matrix(&matrix);
    s21_remove_matrix(&result_matrix);
  }
}
END_TEST

START_TEST(mult_number_zero) {
  srand(time(NULL));
  matrix_t matrix, result_matrix;
  int rows = (int)rand() % 100 + 1, columns = (int)rand() % 100 + 1;
  int result = s21_create_matrix(rows, columns, &matrix);
  ck_assert_int_eq(OK, result);

  result = s21_mult_number(&matrix, (double)rand(), &result_matrix);
  ck_assert_int_eq(OK, result);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      ck_assert_ldouble_eq_tol(result_matrix.matrix[i][j], 0., 0.000001);
    }
  }
  s21_remove_matrix(&result_matrix);

  write_random_matrix(&matrix);
  result = s21_mult_number(&matrix, 0., &result_matrix);
  ck_assert_int_eq(OK, result);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      ck_assert_ldouble_eq_tol(result_matrix.matrix[i][j], 0., 0.000001);
    }
  }
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(mult_number_incorrect_size) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);

  matrix.rows = 0;
  result = s21_mult_number(&matrix, 2., &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);

  matrix.rows = 2;
  matrix.columns = 0;
  result = s21_mult_number(&matrix, 2., &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(mult_square_2x2) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)2., (double)0.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(2, 2, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  expected_result.matrix[0][0] = 8.;
  expected_result.matrix[0][1] = 12.;
  expected_result.matrix[1][0] = 8.;
  expected_result.matrix[1][1] = 12.;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix2, (double)0., (double)0.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  write_iteratively_matrix(&expected_result, (double)0., (double)0.);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)2.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = 10.;
  expected_result.matrix[0][1] = 14.;
  expected_result.matrix[1][0] = 26.;
  expected_result.matrix[1][1] = 38.;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix2, (double)-1., (double)1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = 2.;
  expected_result.matrix[0][1] = 6.;
  expected_result.matrix[1][0] = 2.;
  expected_result.matrix[1][1] = 14.;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)-8., (double)4.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = 20.;
  expected_result.matrix[0][1] = 32.;
  expected_result.matrix[1][0] = -12.;
  expected_result.matrix[1][1] = -16.;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)3., (double)-1.);
  write_iteratively_matrix(&matrix2, (double)0., (double)-1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = -4.;
  expected_result.matrix[0][1] = -9.;
  expected_result.matrix[1][0] = 0.;
  expected_result.matrix[1][1] = -1.;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(mult_col_x_vector) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(3, 1, &matrix1);
  int result2 = s21_create_matrix(1, 3, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)2., (double)0.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(3, 3, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  expected_result.matrix[0][0] = 2.;
  expected_result.matrix[0][1] = 4.;
  expected_result.matrix[0][2] = 6.;
  expected_result.matrix[1][0] = 2.;
  expected_result.matrix[1][1] = 4.;
  expected_result.matrix[1][2] = 6.;
  expected_result.matrix[2][0] = 2.;
  expected_result.matrix[2][1] = 4.;
  expected_result.matrix[2][2] = 6.;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0., (double)0.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  init_valid_matrix(&expected_result);
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)-8., (double)4.);
  write_iteratively_matrix(&matrix2, (double)-1., (double)-1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = 8.;
  expected_result.matrix[0][1] = 16.;
  expected_result.matrix[0][2] = 24.;
  expected_result.matrix[1][0] = 4.;
  expected_result.matrix[1][1] = 8.;
  expected_result.matrix[1][2] = 12.;
  expected_result.matrix[2][0] = 0.;
  expected_result.matrix[2][1] = 0.;
  expected_result.matrix[2][2] = 0.;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)0.1, (double)0.2);
  write_iteratively_matrix(&matrix2, (double)-1.5, (double)0.5);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = -0.15;
  expected_result.matrix[0][1] = -0.1;
  expected_result.matrix[0][2] = -0.05;
  expected_result.matrix[1][0] = -0.45;
  expected_result.matrix[1][1] = -0.3;
  expected_result.matrix[1][2] = -0.15;
  expected_result.matrix[2][0] = -0.75;
  expected_result.matrix[2][1] = -0.5;
  expected_result.matrix[2][2] = -0.25;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_ldouble_eq_tol(result.matrix[i][j],
                               expected_result.matrix[i][j], 0.000001);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(mult_vector_x_col) {
  matrix_t matrix1, matrix2;
  int result1 = s21_create_matrix(1, 4, &matrix1);
  int result2 = s21_create_matrix(4, 1, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  write_iteratively_matrix(&matrix1, (double)2., (double)0.);
  write_iteratively_matrix(&matrix2, (double)1., (double)1.);
  matrix_t result, expected_result;
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  result2 = s21_create_matrix(1, 1, &expected_result);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  expected_result.matrix[0][0] = 20.;
  ck_assert_ldouble_eq_tol(result.matrix[0][0], expected_result.matrix[0][0],
                           0.000001);
  ck_assert_int_eq(result.rows, 1);
  ck_assert_int_eq(result.columns, 1);
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double)1., (double)-1.);
  write_iteratively_matrix(&matrix2, (double)5., (double)1.);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = -18.;
  ck_assert_ldouble_eq_tol(result.matrix[0][0], expected_result.matrix[0][0],
                           0.000001);
  ck_assert_int_eq(result.rows, 1);
  ck_assert_int_eq(result.columns, 1);
  s21_remove_matrix(&result);

  write_iteratively_matrix(&matrix1, (double).00001, (double).00001);
  write_iteratively_matrix(&matrix2, (double).00001, (double).00001);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(OK, result1);
  expected_result.matrix[0][0] = 0.;
  ck_assert_ldouble_eq_tol(result.matrix[0][0], expected_result.matrix[0][0],
                           0.000001);
  ck_assert_int_eq(result.rows, 1);
  ck_assert_int_eq(result.columns, 1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&result);
  s21_remove_matrix(&expected_result);
}
END_TEST

START_TEST(mult_incorrect_matrix) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(2, 2, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  matrix1.rows = 0;
  matrix1.columns = 0;
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  matrix1.rows = 2;
  matrix1.columns = 2;
  matrix2.rows = 0;
  matrix2.columns = 0;
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(INCORRECT_MATRIX, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(mult_wrong_size) {
  matrix_t matrix1, matrix2, result;
  int result1 = s21_create_matrix(2, 2, &matrix1);
  int result2 = s21_create_matrix(1, 2, &matrix2);
  ck_assert_int_eq(OK, result1);
  ck_assert_int_eq(OK, result2);
  result1 = s21_mult_matrix(&matrix1, &matrix2, &result);
  ck_assert_int_eq(CALCULATION_ERROR, result1);
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(transpose_random) {
  srand(time(NULL));
  for (int count = 0; count < 50; count++) {
    matrix_t matrix, result_matrix;
    int rows = (int)rand() % 50 + 1, columns = (int)rand() % 50 + 1;
    int result = s21_create_matrix(rows, columns, &matrix);
    ck_assert_int_eq(OK, result);

    write_random_matrix(&matrix);
    result = s21_transpose(&matrix, &result_matrix);
    ck_assert_int_eq(matrix.rows, result_matrix.columns);
    ck_assert_int_eq(matrix.columns, result_matrix.rows);
    for (int i = 0; i < rows; i++) {
      for (int j = 0; j < columns; j++) {
        ck_assert_ldouble_eq_tol(result_matrix.matrix[j][i],
                                 matrix.matrix[i][j], 0.000001);
      }
    }
    s21_remove_matrix(&matrix);
    s21_remove_matrix(&result_matrix);
  }
}
END_TEST

START_TEST(transpose_incorrect_matrix) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);

  matrix.rows = 0;
  result = s21_transpose(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);

  matrix.rows = 2;
  matrix.columns = 0;
  result = s21_transpose(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_matrix_1x1) {
  srand(time(NULL));
  matrix_t matrix;
  int result = s21_create_matrix(1, 1, &matrix);

  ck_assert_int_eq(OK, result);
  for (int count = 0; count < 50; count++) {
    double element =
        (double)(rand()) / RAND_MAX * pow(-1., rand() % 2) * ULONG_MAX;
    double determinant = 0;

    matrix.matrix[0][0] = element;
    result = s21_determinant(&matrix, &determinant);
    ck_assert_int_eq(OK, result);
    ck_assert_ldouble_eq_tol(element, determinant, 0.000001);
  }
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_2x2_simple) {
  matrix_t matrix;
  double determinant = 0;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);
  write_iteratively_matrix(&matrix, (double)1., (double)1.);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(-2., determinant, 0.000001);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_matrix_2x2_random) {
  matrix_t matrix;
  int result = s21_create_matrix(2, 2, &matrix);

  ck_assert_int_eq(OK, result);
  for (int count = 0; count < 50; count++) {
    double determinant = 0;
    write_random_matrix(&matrix);
    result = s21_determinant(&matrix, &determinant);
    double expected = matrix.matrix[0][0] * matrix.matrix[1][1] -
                      matrix.matrix[1][0] * matrix.matrix[0][1];
    ck_assert_int_eq(OK, result);
    ck_assert_ldouble_eq_tol(expected, determinant, 0.000001);
  }
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_3x3_zero) {
  matrix_t matrix;
  double determinant = 0;
  int result = s21_create_matrix(3, 3, &matrix);
  ck_assert_int_eq(OK, result);
  write_iteratively_matrix(&matrix, (double)1., (double)1.);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(0., determinant, 0.000001);

  write_iteratively_matrix(&matrix, (double)1., (double)2.);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(0., determinant, 0.000001);

  write_iteratively_matrix(&matrix, (double)1., (double)-1.);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(0., determinant, 0.000001);

  write_iteratively_matrix(&matrix, (double)0., (double)2.);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(0., determinant, 0.000001);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_3x3_non_zero) {
  matrix_t matrix;
  double determinant = 0;
  int result = s21_create_matrix(3, 3, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.matrix[0][0] = 1.;
  matrix.matrix[0][1] = 0.;
  matrix.matrix[0][2] = 1.;
  matrix.matrix[1][0] = 1.;
  matrix.matrix[1][1] = 1.;
  matrix.matrix[1][2] = 1.;
  matrix.matrix[2][0] = 0.;
  matrix.matrix[2][1] = 0.;
  matrix.matrix[2][2] = 1.;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(1., determinant, 0.000001);

  matrix.matrix[0][0] = 10.;
  matrix.matrix[0][1] = 0.;
  matrix.matrix[0][2] = 1.;
  matrix.matrix[1][0] = 10.;
  matrix.matrix[1][1] = 1.;
  matrix.matrix[1][2] = 1.;
  matrix.matrix[2][0] = 0.;
  matrix.matrix[2][1] = 0.;
  matrix.matrix[2][2] = 10.;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(100., determinant, 0.000001);

  matrix.matrix[0][0] = 10.;
  matrix.matrix[0][1] = 0.;
  matrix.matrix[0][2] = 1.;
  matrix.matrix[1][0] = 10.;
  matrix.matrix[1][1] = 1.;
  matrix.matrix[1][2] = 1.;
  matrix.matrix[2][0] = -7.;
  matrix.matrix[2][1] = -5.;
  matrix.matrix[2][2] = 10.;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(107., determinant, 0.000001);

  matrix.matrix[0][0] = 1234.;
  matrix.matrix[0][1] = 111.78;
  matrix.matrix[0][2] = -404.1;
  matrix.matrix[1][0] = 10.;
  matrix.matrix[1][1] = 1.;
  matrix.matrix[1][2] = 1.;
  matrix.matrix[2][0] = -7.;
  matrix.matrix[2][1] = -5.;
  matrix.matrix[2][2] = 10.;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(OK, result);
  ck_assert_ldouble_eq_tol(23925.84, determinant, 0.000001);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_random_row_zero) {
  for (int count = 0; count < 10; count++) {
    srand(time(NULL));
    matrix_t matrix;
    double determinant = 0;
    int str = 0, rows = rand() % 50;
    int result = s21_create_matrix(rows, rows, &matrix);
    ck_assert_int_eq(OK, result);
    write_random_matrix(&matrix);
    str = rand() % rows;
    for (int i = 0; i < rows; i++) {
      matrix.matrix[str][i] = 0.;
    }
    result = s21_determinant(&matrix, &determinant);
    ck_assert_int_eq(OK, result);
    ck_assert_ldouble_eq_tol(0., determinant, 0.000001);
    s21_remove_matrix(&matrix);
  }
}
END_TEST

START_TEST(determinant_random_col_zero) {
  for (int count = 0; count < 10; count++) {
    srand(time(NULL));
    matrix_t matrix;
    double determinant = 0;
    int col = 0, rows = rand() % 50;
    int result = s21_create_matrix(rows, rows, &matrix);
    ck_assert_int_eq(OK, result);
    write_random_matrix(&matrix);
    col = rand() % rows;
    for (int i = 0; i < rows; i++) {
      matrix.matrix[i][col] = 0.;
    }
    result = s21_determinant(&matrix, &determinant);
    ck_assert_int_eq(OK, result);
    ck_assert_ldouble_eq_tol(0., determinant, 0.000001);
    s21_remove_matrix(&matrix);
  }
}
END_TEST

START_TEST(determinant_incorrect_matrix) {
  matrix_t matrix;
  double determinant = 0.;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);

  matrix.rows = 0;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(INCORRECT_MATRIX, result);

  matrix.rows = 2;
  matrix.columns = 0;
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(determinant_calc_error) {
  matrix_t matrix;
  double determinant = 0.;
  int result = s21_create_matrix(1, 2, &matrix);
  ck_assert_int_eq(OK, result);
  result = s21_determinant(&matrix, &determinant);
  ck_assert_int_eq(CALCULATION_ERROR, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(complement_from_readme) {
  matrix_t matrix, result_matrix, expected_matrix;
  int result = s21_create_matrix(3, 3, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.matrix[0][0] = 1.;
  matrix.matrix[0][1] = 2.;
  matrix.matrix[0][2] = 3.;
  matrix.matrix[1][0] = 0.;
  matrix.matrix[1][1] = 4.;
  matrix.matrix[1][2] = 2.;
  matrix.matrix[2][0] = 5.;
  matrix.matrix[2][1] = 2.;
  matrix.matrix[2][2] = 1.;
  result = s21_create_matrix(3, 3, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = 0.;
  expected_matrix.matrix[0][1] = 10.;
  expected_matrix.matrix[0][2] = -20.;
  expected_matrix.matrix[1][0] = 4.;
  expected_matrix.matrix[1][1] = -14.;
  expected_matrix.matrix[1][2] = 8.;
  expected_matrix.matrix[2][0] = -8.;
  expected_matrix.matrix[2][1] = -2.;
  expected_matrix.matrix[2][2] = 4.;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&matrix);
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);
}
END_TEST

START_TEST(complement_simple_2x2) {
  matrix_t matrix, result_matrix, expected_matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);
  write_iteratively_matrix(&matrix, (double)1., (double)1.);
  result = s21_create_matrix(2, 2, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = 4.;
  expected_matrix.matrix[0][1] = -3.;
  expected_matrix.matrix[1][0] = -2.;
  expected_matrix.matrix[1][1] = 1.;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);

  write_iteratively_matrix(&matrix, (double)1., (double)0.);
  expected_matrix.matrix[0][0] = 1.;
  expected_matrix.matrix[0][1] = -1.;
  expected_matrix.matrix[1][0] = -1.;
  expected_matrix.matrix[1][1] = 1.;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);

  write_iteratively_matrix(&matrix, (double)0., (double)0.);
  expected_matrix.matrix[0][0] = 0.;
  expected_matrix.matrix[0][1] = 0.;
  expected_matrix.matrix[1][0] = 0.;
  expected_matrix.matrix[1][1] = 0.;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);

  write_iteratively_matrix(&matrix, (double)2., (double)-1.);
  expected_matrix.matrix[0][0] = -1.;
  expected_matrix.matrix[0][1] = 0.;
  expected_matrix.matrix[1][0] = -1.;
  expected_matrix.matrix[1][1] = 2.;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);

  s21_remove_matrix(&matrix);
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);
}
END_TEST

START_TEST(complement_incorrect_matrix) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.rows = 0;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);

  matrix.rows = 2;
  matrix.columns = 0;
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(complement_calc_error) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 1, &matrix);
  ck_assert_int_eq(OK, result);
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(CALCULATION_ERROR, result);
  s21_remove_matrix(&matrix);

  result = s21_create_matrix(1, 1, &matrix);
  ck_assert_int_eq(OK, result);
  result = s21_calc_complements(&matrix, &result_matrix);
  ck_assert_int_eq(CALCULATION_ERROR, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(inverse_from_readme) {
  matrix_t matrix, result_matrix, expected_matrix;
  int result = s21_create_matrix(3, 3, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.matrix[0][0] = 2.;
  matrix.matrix[0][1] = 5.;
  matrix.matrix[0][2] = 7.;
  matrix.matrix[1][0] = 6.;
  matrix.matrix[1][1] = 3.;
  matrix.matrix[1][2] = 4.;
  matrix.matrix[2][0] = 5.;
  matrix.matrix[2][1] = -2.;
  matrix.matrix[2][2] = -3.;
  result = s21_create_matrix(3, 3, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = 1.;
  expected_matrix.matrix[0][1] = -1.;
  expected_matrix.matrix[0][2] = 1.;
  expected_matrix.matrix[1][0] = -38.;
  expected_matrix.matrix[1][1] = 41.;
  expected_matrix.matrix[1][2] = -34.;
  expected_matrix.matrix[2][0] = 27.;
  expected_matrix.matrix[2][1] = -29.;
  expected_matrix.matrix[2][2] = 24.;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&matrix);
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);
}
END_TEST

START_TEST(inverse_matrix_3x3) {
  matrix_t matrix, result_matrix, expected_matrix;
  int result = s21_create_matrix(3, 3, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.matrix[0][0] = 1.;
  matrix.matrix[0][1] = 4.;
  matrix.matrix[0][2] = 2.;
  matrix.matrix[1][0] = 5.;
  matrix.matrix[1][1] = 3.;
  matrix.matrix[1][2] = 2.;
  matrix.matrix[2][0] = 3.;
  matrix.matrix[2][1] = 7.;
  matrix.matrix[2][2] = 1.;
  result = s21_create_matrix(3, 3, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = -0.2444444;
  expected_matrix.matrix[0][1] = 0.2222222;
  expected_matrix.matrix[0][2] = 0.0444444;
  expected_matrix.matrix[1][0] = 0.0222222;
  expected_matrix.matrix[1][1] = -0.1111111;
  expected_matrix.matrix[1][2] = 0.1777778;
  expected_matrix.matrix[2][0] = 0.5777778;
  expected_matrix.matrix[2][1] = 0.1111111;
  expected_matrix.matrix[2][2] = -0.3777778;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);

  matrix.matrix[0][0] = 4.;
  matrix.matrix[0][1] = 3.;
  matrix.matrix[0][2] = 2.;
  matrix.matrix[1][0] = 1.;
  matrix.matrix[1][1] = 2.;
  matrix.matrix[1][2] = 3.;
  matrix.matrix[2][0] = 4.;
  matrix.matrix[2][1] = 5.;
  matrix.matrix[2][2] = 5.;
  result = s21_create_matrix(3, 3, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = 1;
  expected_matrix.matrix[0][1] = 1.;
  expected_matrix.matrix[0][2] = -1.;
  expected_matrix.matrix[1][0] = -1.4;
  expected_matrix.matrix[1][1] = -2.4;
  expected_matrix.matrix[1][2] = 2.;
  expected_matrix.matrix[2][0] = 0.6;
  expected_matrix.matrix[2][1] = 1.6;
  expected_matrix.matrix[2][2] = -1.;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);

  matrix.matrix[0][0] = 4.;
  matrix.matrix[0][1] = 3.;
  matrix.matrix[0][2] = 2.;
  matrix.matrix[1][0] = 1.;
  matrix.matrix[1][1] = 2.;
  matrix.matrix[1][2] = 3.;
  matrix.matrix[2][0] = 4.;
  matrix.matrix[2][1] = 5.;
  matrix.matrix[2][2] = 5.;
  result = s21_create_matrix(3, 3, &expected_matrix);
  ck_assert_int_eq(OK, result);
  expected_matrix.matrix[0][0] = 1;
  expected_matrix.matrix[0][1] = 1.;
  expected_matrix.matrix[0][2] = -1.;
  expected_matrix.matrix[1][0] = -1.4;
  expected_matrix.matrix[1][1] = -2.4;
  expected_matrix.matrix[1][2] = 2.;
  expected_matrix.matrix[2][0] = 0.6;
  expected_matrix.matrix[2][1] = 1.6;
  expected_matrix.matrix[2][2] = -1.;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(OK, result);
  ck_assert_int_eq(SUCCESS, s21_eq_matrix(&result_matrix, &expected_matrix));

  s21_remove_matrix(&matrix);
  s21_remove_matrix(&result_matrix);
  s21_remove_matrix(&expected_matrix);
}
END_TEST

START_TEST(inverse_matrix_1x1) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(1, 1, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.matrix[0][0] = 2.;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_ldouble_eq_tol(0.5, result_matrix.matrix[0][0], 0.000001);
  s21_remove_matrix(&matrix);
  s21_remove_matrix(&result_matrix);
}
END_TEST

START_TEST(inverse_incorrect_matrix) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);
  matrix.rows = 0;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);

  matrix.rows = 2;
  matrix.columns = 0;
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(INCORRECT_MATRIX, result);
  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(inverse_calc_error) {
  matrix_t matrix, result_matrix;
  int result = s21_create_matrix(2, 1, &matrix);
  ck_assert_int_eq(OK, result);
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(CALCULATION_ERROR, result);
  s21_remove_matrix(&matrix);

  result = s21_create_matrix(2, 2, &matrix);
  ck_assert_int_eq(OK, result);
  write_iteratively_matrix(&matrix, (double)3., (double)0.);
  result = s21_inverse_matrix(&matrix, &result_matrix);
  ck_assert_int_eq(CALCULATION_ERROR, result);
  s21_remove_matrix(&matrix);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("s21_create_matrix_test");
  TCase *tc1_1 = tcase_create("create_no_mistake");
  TCase *tc1_2 = tcase_create("create_with_mistakes");
  Suite *s2 = suite_create("s21_remove_matrix_test");
  TCase *tc2_1 = tcase_create("remove_no_mistake");
  TCase *tc2_2 = tcase_create("remove_with_mistake");
  Suite *s3 = suite_create("s21_eq_matrix_test");
  TCase *tc3_1 = tcase_create("equivalent_matrix");
  TCase *tc3_2 = tcase_create("not_equivalent_matrix");
  Suite *s4 = suite_create("s21_sum_matrix_test");
  TCase *tc4_1 = tcase_create("sum_valid_matrix");
  TCase *tc4_2 = tcase_create("sum_matrix_not_valid");
  Suite *s5 = suite_create("s21_sub_matrix_test");
  TCase *tc5_1 = tcase_create("sub_valid_matrix");
  TCase *tc5_2 = tcase_create("sub_matrix_not_valid");
  Suite *s6 = suite_create("s21_mult_number_test");
  TCase *tc6_1 = tcase_create("mult_number_valid_matrix");
  TCase *tc6_2 = tcase_create("mult_number_not_valid");
  Suite *s7 = suite_create("s21_mult_matrix_test");
  TCase *tc7_1 = tcase_create("mult_matrix_valid");
  TCase *tc7_2 = tcase_create("mult_matrix_not_valid");
  Suite *s8 = suite_create("s21_transpose_test");
  TCase *tc8_1 = tcase_create("transpose_valid_matrix");
  TCase *tc8_2 = tcase_create("transpose_not_valid");
  Suite *s9 = suite_create("s21_determinant_test");
  TCase *tc9_1 = tcase_create("determinant_valid_matrix");
  TCase *tc9_2 = tcase_create("determinant_not_valid");
  Suite *s10 = suite_create("s21_calc_complements_test");
  TCase *tc10_1 = tcase_create("complements_valid");
  TCase *tc10_2 = tcase_create("complement_not_valid");
  Suite *s11 = suite_create("s21_inverse_matrix_test");
  TCase *tc11_1 = tcase_create("inverse_valid_matrix");
  TCase *tc11_2 = tcase_create("inverse_not_valid");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, create_no_mistake_square);
  tcase_add_test(tc1_1, create_no_mistake_vector_1);
  tcase_add_test(tc1_1, create_no_mistake_vector_2);
  tcase_add_test(tc1_1, create_no_mistake_rectangle);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, create_mistake_incorrect_size_1);
  tcase_add_test(tc1_2, create_mistake_incorrect_size_2);
  tcase_add_test(tc1_2, create_mistake_null_poiner);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, remove_matrix_correct);
  suite_add_tcase(s2, tc2_2);
  tcase_add_test(tc2_2, remove_matrix_incorrect_pointer);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, eq_square_matrix);
  tcase_add_test(tc3_1, eq_rectangle_matrix);
  suite_add_tcase(s3, tc3_2);
  tcase_add_test(tc3_2, eq_matrix_same_size);
  tcase_add_test(tc3_2, eq_matrix_diff_size);
  tcase_add_test(tc3_2, eq_matrix_wrong_matrix);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, sum_square_2x2);
  tcase_add_test(tc4_1, sum_vector);
  tcase_add_test(tc4_1, sum_matrix_3x3);
  tcase_add_test(tc4_1, sum_matrix_random);
  suite_add_tcase(s4, tc4_2);
  tcase_add_test(tc4_2, sum_incorrect_matrix);
  tcase_add_test(tc4_2, sum_wrong_size);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, sub_square_2x2);
  tcase_add_test(tc5_1, sub_vector);
  tcase_add_test(tc5_1, sub_matrix_3x3);
  tcase_add_test(tc5_1, sub_matrix_random);
  suite_add_tcase(s5, tc5_2);
  tcase_add_test(tc5_2, sub_incorrect_matrix);
  tcase_add_test(tc5_2, sub_wrong_size);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, mult_number_square_2x2);
  tcase_add_test(tc6_1, mult_number_random_size);
  tcase_add_test(tc6_1, mult_number_zero);
  suite_add_tcase(s6, tc6_2);
  tcase_add_test(tc6_2, mult_number_incorrect_size);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, mult_square_2x2);
  tcase_add_test(tc7_1, mult_col_x_vector);
  tcase_add_test(tc7_1, mult_vector_x_col);
  suite_add_tcase(s7, tc7_2);
  tcase_add_test(tc7_2, mult_incorrect_matrix);
  tcase_add_test(tc7_2, mult_wrong_size);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, transpose_random);
  suite_add_tcase(s8, tc8_2);
  tcase_add_test(tc8_2, transpose_incorrect_matrix);
  suite_add_tcase(s9, tc9_1);
  tcase_add_test(tc9_1, determinant_matrix_1x1);
  tcase_add_test(tc9_1, determinant_2x2_simple);
  tcase_add_test(tc9_1, determinant_matrix_2x2_random);
  tcase_add_test(tc9_1, determinant_3x3_zero);
  tcase_add_test(tc9_1, determinant_3x3_non_zero);
  tcase_add_test(tc9_1, determinant_random_row_zero);
  tcase_add_test(tc9_1, determinant_random_col_zero);
  suite_add_tcase(s9, tc9_2);
  tcase_add_test(tc9_2, determinant_incorrect_matrix);
  tcase_add_test(tc9_2, determinant_calc_error);
  suite_add_tcase(s10, tc10_1);
  tcase_add_test(tc10_1, complement_from_readme);
  tcase_add_test(tc10_1, complement_simple_2x2);
  suite_add_tcase(s10, tc10_2);
  tcase_add_test(tc10_2, complement_incorrect_matrix);
  tcase_add_test(tc10_2, complement_calc_error);
  suite_add_tcase(s11, tc11_1);
  tcase_add_test(tc11_1, inverse_from_readme);
  tcase_add_test(tc11_1, inverse_matrix_3x3);
  tcase_add_test(tc11_1, inverse_matrix_1x1);
  suite_add_tcase(s11, tc11_2);
  tcase_add_test(tc11_2, inverse_incorrect_matrix);
  tcase_add_test(tc11_2, inverse_calc_error);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);
  srunner_add_suite(sr, s9);
  srunner_add_suite(sr, s10);
  srunner_add_suite(sr, s11);

  srunner_run_all(sr, CK_VERBOSE);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
